local chapters = require('lib/chapters')

local function chs()
	return {
		{time = 0, title = 'Intro'},
		{time = 30, title = 'Sponsor'},
		{time = 90, title = ''}, -- untitled
		{time = 150, title = 'Outro'},
	}
end

describe('chapters.chapter_at_time', function()
	it('returns the chapter whose span contains t', function()
		local ch, i = chapters.chapter_at_time(chs(), 45)
		assert.are.equal('Sponsor', ch.title)
		assert.are.equal(2, i)
	end)

	it('returns the exact chapter when t lands on a boundary', function()
		local ch, i = chapters.chapter_at_time(chs(), 90)
		assert.are.equal(3, i)
		assert.are.equal(90, ch.time)
	end)

	it('returns the last chapter past its start', function()
		local _, i = chapters.chapter_at_time(chs(), 9999)
		assert.are.equal(4, i)
	end)

	it('returns nil before the first chapter start', function()
		local list = {{time = 10, title = 'A'}}
		assert.is_nil(chapters.chapter_at_time(list, 5))
	end)

	it('returns nil for empty or missing input', function()
		assert.is_nil(chapters.chapter_at_time({}, 5))
		assert.is_nil(chapters.chapter_at_time(nil, 5))
		assert.is_nil(chapters.chapter_at_time(chs(), nil))
	end)
end)

describe('chapters.next_chapter', function()
	it('returns the following chapter', function()
		assert.are.equal('Outro', chapters.next_chapter(chs(), 3).title)
	end)
	it('returns nil on the last chapter', function()
		assert.is_nil(chapters.next_chapter(chs(), 4))
	end)
	it('returns nil for missing input', function()
		assert.is_nil(chapters.next_chapter(nil, 1))
		assert.is_nil(chapters.next_chapter(chs(), nil))
	end)
end)

describe('chapters.chapter_span', function()
	it('spans from this chapter start to the next chapter start', function()
		local span = chapters.chapter_span(chs(), 2, 200)
		assert.are.equal(30, span.start)
		assert.are.equal(90, span.stop)
	end)
	it('uses duration as the last chapter stop', function()
		local span = chapters.chapter_span(chs(), 4, 200)
		assert.are.equal(150, span.start)
		assert.are.equal(200, span.stop)
	end)
	it('returns nil for a non-existent index', function()
		assert.is_nil(chapters.chapter_span(chs(), 9, 200))
	end)
end)

describe('chapters.chapter_label', function()
	it('uses the title when present', function()
		assert.are.equal('Intro', chapters.chapter_label({title = 'Intro'}, 1))
	end)
	it('falls back to Chapter N when untitled', function()
		assert.are.equal('Chapter 3', chapters.chapter_label({title = ''}, 3))
		assert.are.equal('Chapter 2', chapters.chapter_label({}, 2))
	end)
	it('returns nil for a nil chapter', function()
		assert.is_nil(chapters.chapter_label(nil, 1))
	end)
end)

describe('chapters.should_show_next_video', function()
	it('shows inside the threshold window with a next item', function()
		assert.is_true(chapters.should_show_next_video(540, 600, 120, true))
		assert.is_true(chapters.should_show_next_video(480, 600, 120, true)) -- exactly 120 left
	end)
	it('hides outside the threshold window', function()
		assert.is_false(chapters.should_show_next_video(400, 600, 120, true))
	end)
	it('hides without a next playlist item', function()
		assert.is_false(chapters.should_show_next_video(590, 600, 120, false))
	end)
	it('hides on invalid duration/threshold', function()
		assert.is_false(chapters.should_show_next_video(10, 0, 120, true))
		assert.is_false(chapters.should_show_next_video(590, 600, 0, true))
		assert.is_false(chapters.should_show_next_video(nil, 600, 120, true))
	end)
end)

describe('chapters.truncate', function()
	it('leaves short strings untouched', function()
		assert.are.equal('Intro', chapters.truncate('Intro', 10))
	end)
	it('truncates long strings with an ellipsis', function()
		assert.are.equal('abcde…', chapters.truncate('abcdefghij', 5))
	end)
	it('does not split multibyte codepoints', function()
		-- 'héllo' where é is 2 bytes; truncating to 2 codepoints -> 'hé…'
		assert.are.equal('hé…', chapters.truncate('héllo', 2))
	end)
	it('passes through on nil/zero max', function()
		assert.is_nil(chapters.truncate(nil, 5))
		assert.are.equal('abc', chapters.truncate('abc', 0))
	end)
end)
